---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Ejecutando script de pre-build..."
      - chmod +x prebuild.sh
      - ./prebuild.sh

  build:
    commands:
      - echo "Construyendo la imagen del backend..."
      - docker build -t $BACKEND_URI:$IMAGE_TAG ./backend
      - echo "Construyendo la imagen del frontend..."
      - docker build -t $FRONTEND_URI:$IMAGE_TAG ./frontend

  post_build:
    commands:
      - echo "Subiendo la imagen del backend a ECR..."
      - docker push $BACKEND_URI:$IMAGE_TAG
      - echo "Subiendo la imagen del frontend a ECR..."
      - docker push $FRONTEND_URI:$IMAGE_TAG

