---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Ejecutando script de pre-build..."
      - chmod +x prebuild.sh
      - ./prebuild.sh
      # Generamos las variables de entorno para Docker
      - export BACKEND_URI=$AWS_ACCOUNT_ID_MARCO.dkr.ecr.$AWS_REGION_MARCO.amazonaws.com/$ECR_BACKEND_REPO
      - export FRONTEND_URI=$AWS_ACCOUNT_ID_MARCO.dkr.ecr.$AWS_REGION_MARCO.amazonaws.com/$ECR_FRONTEND_REPO
      - export IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | cut -d: -f2 | cut -c1-7)
      - echo "BACKEND_URI=$BACKEND_URI, FRONTEND_URI=$FRONTEND_URI, IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Construyendo la imagen del backend..."
      - docker build -t $BACKEND_URI:$IMAGE_TAG ./backend
      - echo "Construyendo la imagen del frontend..."
      - docker build -t $FRONTEND_URI:$IMAGE_TAG ./frontend

  post_build:
    commands:
      - echo "Subiendo la imagen del backend a ECR..."
      - docker push $BACKEND_URI:$IMAGE_TAG
      - echo "Subiendo la imagen del frontend a ECR..."
      - docker push $FRONTEND_URI:$IMAGE_TAG
      - echo "Build y push finalizados."
