# Usamos una imagen base de Java 17
FROM amazoncorretto:17-alpine-jdk

# Directorio de trabajo
WORKDIR /app

# Argumento opcional para el JAR
ARG JAR_FILE=target/*.jar

# Copiamos el JAR compilado al contenedor
COPY ${JAR_FILE} app.jar

# Exponemos el puerto 8080
EXPOSE 8080

# Comando al iniciar el contenedor
ENTRYPOINT ["java","-jar","/app.jar"]
