FROM openjdk:17-alpine

# Solo ponemos un archivo de ejemplo para que el contenedor tenga algo
RUN echo 'Hola backend' > /app.txt

WORKDIR /

# Entrypoint dummy para que Dockerfile funcione
CMD ["cat", "/app.txt"]
